version: '3.8'

services:
  web:
    image: nginx:1.25-alpine
    container_name: bulletin-board-nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulletin-board-php
    volumes:
      - ./code:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      - DB_HOST=db
      - DB_NAME=web
      - DB_USER=root
      - DB_PASS=helloworld
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bulletin-board-mysql
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: web
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local